'''
Created on Jun 11, 2016

@author: richd
'''


ONE = "SONAR_KEY_ONE"
TWO = "SONAR_KEY_TWO"
THREE = "SONAR_KEY_THREE"
FOUR = "SONAR_KEY_FOUR"
FIVE = "SONAR_KEY_FIVE"
SIX = "SONAR_KEY_SIX"
SEVEN = "SONAR_KEY_SEVEN"
EIGHT = "SONAR_KEY_EIGHT"
NINE = "SONAR_KEY_NINE"
TEN = "SONAR_KEY_TEN"